import { defineEventHandler, readBody } from 'h3'
import { Resend } from 'resend'

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const { email } = body

  if (!email) {
    return { status: 'error', message: 'Email is required' }
  }

  const resend = new Resend(process.env.RESEND_API_KEY)

  try {
    const { data, error } = await resend.emails.send({
      from: 'SmartSaha <no-reply@smart-saha.com>',
      to: ["smartsahaapp@gmail.com"],
      subject: 'New Subscription',
      html: `
        <div style="font-family: Arial, sans-serif; color: #1a1a1a;">
          <h2 style="color: #112830;">New Subscription</h2>
          <p><strong>Email:</strong> ${email}</p>
          <p style="margin-top: 12px; font-size: 0.9rem; color: #555;">Generated by SmartSaha subscription form.</p>
        </div>
      `
    })

    if (error) {
      console.error('Resend Error:', error)
      return { status: 'error', message: 'Failed to send email.' }
    }

    return { status: 'success', message: 'Subscription email sent.', data }
  } catch (err) {
    console.error('System Error:', err)
    return { status: 'error', message: 'Failed to send email.' }
  }
})
