import { defineEventHandler, readBody } from 'h3'
import nodemailer from 'nodemailer'

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const { email } = body

  if (!email) {
    return { status: 'error', message: 'Email is required' }
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.CONTACT_EMAIL,
      pass: process.env.CONTACT_EMAIL_PASS
    }
  })

  const mailOptions = {
    from: `"SmartSaha Subscription" <${process.env.CONTACT_EMAIL}>`,
    to: process.env.CONTACT_EMAIL, 
    subject: 'New Subscription',
    html: `
      <div style="font-family: Arial, sans-serif; color: #1a1a1a;">
        <h2 style="color: #112830;">New Subscription</h2>
        <p><strong>Email:</strong> ${email}</p>
        <p style="margin-top: 12px; font-size: 0.9rem; color: #555;">Generated by SmartSaha subscription form.</p>
      </div>
    `
  }

  try {
    await transporter.sendMail(mailOptions)
    return { status: 'success', message: 'Subscription email sent.' }
  } catch (err) {
    console.error(err)
    return { status: 'error', message: 'Failed to send email.' }
  }
})
